# Generated by Django 4.0 on 2022-05-07 05:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('discipline', models.CharField(max_length=32)),
                ('params', models.JSONField(null=True)),
                ('prev_state', models.CharField(max_length=4096, null=True)),
                ('last_move', models.CharField(max_length=32, null=True)),
                ('state', models.CharField(max_length=4096, null=True)),
                ('history', models.JSONField(null=True)),
                ('current_player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='compman.player')),
                ('first_player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='compman.player')),
                ('second_player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='compman.player')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
